Update JRQ_configure_and_create_project.yaml

diff --git a/.github/workflows/JRQ_configure_and_create_project.yaml b/.github/workflows/JRQ_configure_and_create_project.yaml
--- a/.github/workflows/JRQ_configure_and_create_project.yaml
+++ b/.github/workflows/JRQ_configure_and_create_project.yaml
@@ -19,13 +19,26 @@ on:
         type: text
 
 jobs:
+  validate_dependencies:
+    name: 'Validating dependencies'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate dependencies
+        run: |
+          if [[ ${{ github.event.inputs.CREATE_MSSQL_DB }} == true ]]; then
+            if [[ -z "${{ github.event.inputs.DB_ADMIN_PWD }}" ]]; then
+               echo "DB Admin password required"
+               exit 1
+            fi
+          fi
+          
   format_prj_coode:
     outputs:
       prj_code_lower: ${{ steps.var.outputs.prj_code_lower}}
       prj_code_upper: ${{ steps.var.outputs.prj_code_upper}}
     runs-on: "ubuntu-latest"
     steps:
-      - name: Setting prj code to lower
+      - name: Setting prj code to lower and upper cases
         uses: actions/github-script@v6
         id: var
         with:
@@ -33,7 +46,7 @@ jobs:
             core.setOutput('prj_code_lower', 'JRQ'.toLowerCase().replaceAll(/[/.]/g, '-').trim('-'));
             core.setOutput('prj_code_upper', 'JRQ'.toUpperCase().replaceAll(/[/.]/g, '-').trim('-'));    
   
-  check-if-configured:
+  check-if-params-file-exists:
     needs: [format_prj_coode]
     name: Checking if parameters file exists
     runs-on: ubuntu-latest
@@ -54,7 +67,7 @@ jobs:
           exit 1
 
   configure_projects:
-    needs: [check-if-configured,format_prj_coode]
+    needs: [check-if-params-file-exists,format_prj_coode]
     name: 'Configuring the projects base / frontend-aks / k8s'
     runs-on: ubuntu-latest
     env:
@@ -62,12 +75,12 @@ jobs:
       PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
     steps:
     - uses: actions/checkout@v4
-    - name: Load from file
+    - name: Load parameters from file
       uses: cardinalby/export-env-action@v1
       with:
         envFile: 'params/${{ env.PROJECT_CODE_UPPERCASE}}_params.env'
         expand: 'true'
-    - name: Check values
+    - name: Checking the loaded parameters
       run: |
         echo "env.PROJECT_CODE: '${{env.PROJECT_CODE}}'" 
         echo "env.VNET_SUPERNET: '${{env.VNET_SUPERNET}}'" 
@@ -126,6 +139,54 @@ jobs:
         git commit -m "Confirmation of project configuration"
         git push
 
+    - name: Check out repository code JRQ-k8s
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-JRQ-k8s
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Inject variables for JRQ-k8s
+      run: |
+        sed -i 's#VAR_TEMPLATE_LOAD_BALANCER_IP#${{ env.LOAD_BALANCER_IP }}#g' files/chart_values/nginx-ingress-controller-values.yaml
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#${{ env.PROJECT_CODE_LOWERCASE}}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#${{ env.PROJECT_CODE_LOWERCASE}}#g" backend_config.hcl
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#${{ env.PROJECT_CODE_UPPERCASE}}#g" .github/workflows/create-dynamicepehemral-k8s.yaml
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#${{ env.PROJECT_CODE_UPPERCASE}}#g" .github/workflows/destroy-dynamicepehemral-k8s.yaml
+    - name: Create KEYCLOAK_ARGOCD_CLIENT_SECRET secret for JRQ-k8s
+      uses: hmanzur/actions-set-secret@v2.0.0
+      with:
+        name: "${{ env.PROJECT_CODE_UPPERCASE}}_KEYCLOAK_ARGOCD_CLIENT_SECRET"
+        value: "${{ env.KEYCLOAK_ARGOCD_CLIENT_SECRET }}"
+        repository: 'ES-BAR-MEV'
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+        org: true
+        visibility: 'private'
+    - name: Create DB_ADMIN_PWD secret for JRQ-k8s
+      if: github.event.inputs.CREATE_MSSQL_DB == 'true'
+      uses: hmanzur/actions-set-secret@v2.0.0
+      with:
+        name: "${{ env.PROJECT_CODE_UPPERCASE}}_DB_ADMIN_PWD"
+        value: "${{ env.DB_ADMIN_PWD}}"
+        repository: 'ES-BAR-MEV'
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+        org: true
+        visibility: 'private'
+    - name: Enable DDBB creation for JRQ-k8s
+      if: env.CREATE_MSSQL_DB == 'true'
+      run: |
+        sed -i 's#VAR_TEMPLATE_CREATE_MSSQL_DB#true#g' variables.tf
+    - name: Disable DDBB creation for JRQ-k8s
+      if: env.CREATE_MSSQL_DB == 'false'
+      run: |
+        sed -i 's#VAR_TEMPLATE_CREATE_MSSQL_DB#false#g' variables.tf
+    - name: Creating cfg-applied.txt file for JRQ-k8s
+      run: |
+        echo "CONFIGURATION APPLIED. DO NOT DELETE THIS FILE" >> cfg-applied.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
+
   push_run_creation_workflow_file:
     needs: [configure_projects]
     name: 'Creating the projects base / frontend-aks / k8s'
@@ -151,6 +212,20 @@ jobs:
         repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-JRQ-frontend-aks
         token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
     - name: Create the file run_creation_workflow.txt for JRQ-frontend-aks
+      run: |
+        echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> run_creation_workflow.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
+
+    - name: Check out repository code for JRQ-k8s
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-JRQ-k8s
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Create the file run_creation_workflow.txt for JRQ-k8s
       run: |
         echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> run_creation_workflow.txt
         git config --global user.name "Configure Project"
