Update TEMPLATE_DO_NOT_DELETE.yaml

diff --git a/.github/workflows/TEMPLATE_DO_NOT_DELETE.yaml b/.github/workflows/TEMPLATE_DO_NOT_DELETE.yaml
--- a/.github/workflows/TEMPLATE_DO_NOT_DELETE.yaml
+++ b/.github/workflows/TEMPLATE_DO_NOT_DELETE.yaml
@@ -1,4 +1,4 @@
-name: Configur/Create VAR_TEMPLATE_PROJECT_CODE_UPPERCASE
+name: Configur/Create OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE project
 on:
   workflow_dispatch:
     inputs:
@@ -19,68 +19,51 @@ on:
         type: text
 
 jobs:
-  format_prj_coode:
-    outputs:
-      prj_code_lower: ${{ steps.var.outputs.prj_code_lower}}
-      prj_code_upper: ${{ steps.var.outputs.prj_code_upper}}
-    runs-on: "ubuntu-latest"
+  validate_dependencies:
+    name: 'Validating dependencies'
+    runs-on: ubuntu-latest
     steps:
-      - name: Setting prj code to lower
-        uses: actions/github-script@v6
-        id: var
-        with:
-          script: |
-            core.setOutput('prj_code_lower', 'VAR_TEMPLATE_PROJECT_CODE_UPPERCASE'.toLowerCase().replaceAll(/[/.]/g, '-').trim('-'));
-            core.setOutput('prj_code_upper', 'VAR_TEMPLATE_PROJECT_CODE_UPPERCASE'.toUpperCase().replaceAll(/[/.]/g, '-').trim('-'));    
+      - name: Validate dependencies
+        run: |
+          if [[ ${{ github.event.inputs.CREATE_MSSQL_DB }} == true ]]; then
+            if [[ -z "${{ github.event.inputs.DB_ADMIN_PWD }}" ]]; then
+               echo "DB Admin password required"
+               exit 1
+            fi
+          fi
   
-  check-if-configured:
-    needs: [format_prj_coode]
-    name: Check if project configuration is done
+  check-if-params-file-exists:
+    needs: [validate_dependencies]
+    name: Checking if parameters file exists
     runs-on: ubuntu-latest
     outputs:
       status: ${{ steps.early.conclusion }}
     steps:
       - name: Check out repository code
-        uses: actions/checkout@v3
-      - name: Checking params/VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env file existence
+        uses: actions/checkout@v4
+      - name: Checking params/OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env file existence
         id: check_files
         uses: andstor/file-existence-action@v3
         with:
-          files:  'params/VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env'
+          files:  'params/OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env'
       - name: Configuration is done
         if: steps.check_files.outputs.files_exists != 'true'
         run: |
-          echo "THE CONFIGURATION FILE VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env DOES NOT EXISTS, PLEASE CONFIGURE IT"
+          echo "THE CONFIGURATION FILE OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env DOES NOT EXISTS, PLEASE CONFIGURE IT"
           exit 1
 
-  load-env-vars:
-    needs: [check-if-configured,format_prj_coode]
-    name: 'Load env vars'
+  configure_projects:
+    needs: [check-if-params-file-exists]
+    name: 'Configuring the projects base / frontend-aks / k8s'
     runs-on: ubuntu-latest
-    outputs:
-      env_PROJECT_CODE: ${{ steps.export_var.outputs.env_PROJECT_CODE }}
-      env_VNET_SUPERNET: ${{ steps.export_var.outputs.env_VNET_SUPERNET }}
-      env_SUBNETS_COMMON_IP: ${{ steps.export_var.outputs.env_SUBNETS_COMMON_IP }}
-      env_SUBNETS_APPGW_IP: ${{ steps.export_var.outputs.env_SUBNETS_APPGW_IP }}
-      env_SUBNETS_APPGW_PRIVATE_IP_ADDRESS: ${{ steps.export_var.outputs.env_SUBNETS_APPGW_PRIVATE_IP_ADDRESS }}
-      env_SUBNETS_AKS_NODE_IP: ${{ steps.export_var.outputs.env_SUBNETS_AKS_NODE_IP }}
-      env_NSGS_APPGW_DESTINATION_ADDRESS_PREFIX: ${{ steps.export_var.outputs.env_NSGS_APPGW_DESTINATION_ADDRESS_PREFIX }}
-      env_APPGW_LISTENERS_WILDCARD_BACKENDSIPS: ${{ steps.export_var.outputs.env_APPGW_LISTENERS_WILDCARD_BACKENDSIPS }}
-      env_LOAD_BALANCER_IP: ${{ steps.export_var.outputs.env_LOAD_BALANCER_IP }}
-      env_KEYCLOAK_ARGOCD_CLIENT_SECRET: ${{ steps.export_var.outputs.env_KEYCLOAK_ARGOCD_CLIENT_SECRET }}
-      env_CREATE_MSSQL_DB: ${{ steps.export_var.outputs.env_CREATE_MSSQL_DB }}
-      env_env_DB_ADMIN_PWD: ${{ steps.export_var.outputs.env_DB_ADMIN_PWD }}
-    env:
-      PROJECT_CODE_LOWERCASE: ${{ needs.format_prj_coode.outputs.prj_code_lower }}
-      PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
     steps:
     - uses: actions/checkout@v4
-    - name: Load from file
+    - name: Load parameters from file
       uses: cardinalby/export-env-action@v1
       with:
-        envFile: 'params/${{ env.PROJECT_CODE_UPPERCASE}}_params.env'
+        envFile: 'params/OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_params.env'
         expand: 'true'
-    - name: Check values
+    - name: Checking the loaded parameters
       run: |
         echo "env.PROJECT_CODE: '${{env.PROJECT_CODE}}'" 
         echo "env.VNET_SUPERNET: '${{env.VNET_SUPERNET}}'" 
@@ -93,120 +76,143 @@ jobs:
         echo "env.LOAD_BALANCER_IP: '${{env.LOAD_BALANCER_IP}}'" 
         echo "env.KEYCLOAK_ARGOCD_CLIENT_SECRET: '${{env.KEYCLOAK_ARGOCD_CLIENT_SECRET}}'" 
         echo "env.CREATE_MSSQL_DB: '${{env.CREATE_MSSQL_DB}}'" 
-        echo "env.DB_ADMIN_PWD: '${{env.DB_ADMIN_PWD}}'" 
-    
-    - name: Export values
-      id: export_var
+        echo "env.DB_ADMIN_PWD: '${{env.DB_ADMIN_PWD}}'"
+    - name: Check out repository code OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Inject variables for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
       run: |
-        echo "env_PROJECT_CODE=${{env.PROJECT_CODE}}" >> $GITHUB_OUTPUT
-        echo "env_VNET_SUPERNET=${{env.VNET_SUPERNET}}" >> $GITHUB_OUTPUT
-        echo "env_SUBNETS_COMMON_IP=${{env.SUBNETS_COMMON_IP}}" >> $GITHUB_OUTPUT
-        echo "env_SUBNETS_APPGW_IP=${{env.SUBNETS_APPGW_IP}}" >> $GITHUB_OUTPUT
-        echo "env_SUBNETS_APPGW_PRIVATE_IP_ADDRESS=${{env.SUBNETS_APPGW_PRIVATE_IP_ADDRESS}}" >> $GITHUB_OUTPUT
-        echo "env_SUBNETS_AKS_NODE_IP=${{env.SUBNETS_AKS_NODE_IP}}" >> $GITHUB_OUTPUT
-        echo "env_NSGS_APPGW_DESTINATION_ADDRESS_PREFIX=${{env.NSGS_APPGW_DESTINATION_ADDRESS_PREFIX}}" >> $GITHUB_OUTPUT
-        echo "env_APPGW_LISTENERS_WILDCARD_BACKENDSIPS=${{env.APPGW_LISTENERS_WILDCARD_BACKENDSIPS}}" >> $GITHUB_OUTPUT
-        echo "env_LOAD_BALANCER_IP=${{env.LOAD_BALANCER_IP}}" >> $GITHUB_OUTPUT
-        echo "env_KEYCLOAK_ARGOCD_CLIENT_SECRET=${{env.KEYCLOAK_ARGOCD_CLIENT_SECRET}}" >> $GITHUB_OUTPUT
-        echo "env_CREATE_MSSQL_DB=${{env.CREATE_MSSQL_DB}}" >> $GITHUB_OUTPUT
-        echo "env_DB_ADMIN_PWD=${{env.DB_ADMIN_PWD}}"  >> $GITHUB_OUTPUT
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" backend_config.hcl
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_VNET_SUPERNET#${{ env.VNET_SUPERNET }}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_SUBNETS_COMMON_IP#${{ env.SUBNETS_COMMON_IP }}#g" terraform.tfvars.json
+    - name: Creating cfg-applied.txt file for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+      run: |
+        echo "CONFIGURATION APPLIED. DO NOT DELETE THIS FILE" >> cfg-applied.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
 
-  call-workflow-base:
-    needs: [load-env-vars]
-    name: 'Calling the external BASE workflow to configure and create the project'
-    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base/.github/workflows/mandatory-project-configuration-called.yaml@main
-    with:
-      PROJECT_CODE: ${{ needs.load-env-vars.outputs.env_PROJECT_CODE }}
-      VNET_SUPERNET: ${{ needs.load-env-vars.outputs.env_VNET_SUPERNET }}
-      SUBNETS_COMMON_IP: ${{ needs.load-env-vars.outputs.env_SUBNETS_COMMON_IP }}
+    - name: Check out repository code OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-fronend-aks
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Inject variables for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-fronend-aks
+      run: |
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" backend_config.hcl
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" frt_appgw.tf
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" frt_waf_custom_rules.tf
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_SUBNETS_APPGW_IP#${{ env.SUBNETS_APPGW_IP }}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_SUBNETS_APPGW_PRIVATE_IP_ADDRESS#${{ env.SUBNETS_APPGW_PRIVATE_IP_ADDRESS }}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_SUBNETS_AKS_NODE_IP#${{ env.SUBNETS_AKS_NODE_IP }}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_NSGS_APPGW_DESTINATION_ADDRESS_PREFIX#${{ env.NSGS_APPGW_DESTINATION_ADDRESS_PREFIX }}#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_APPGW_LISTENERS_WILDCARD_BACKENDSIPS#${{ env.APPGW_LISTENERS_WILDCARD_BACKENDSIPS }}#g" terraform.tfvars.json
+    - name: Creating cfg-applied.txt file for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-fronend-aks
+      run: |
+        echo "CONFIGURATION APPLIED. DO NOT DELETE THIS FILE" >> cfg-applied.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
 
-  call-workflow-frontend:
-    needs: [call-workflow-base,load-env-vars]
-    name: 'Calling the external FRONTEND+AKS workflow to configure and create the project'
-    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks/.github/workflows/mandatory-project-configuration-called.yaml@main
-    with:
-      PROJECT_CODE: ${{  needs.load-env-vars.outputs.env_PROJECT_CODE }}
-      SUBNETS_APPGW_IP: ${{  needs.load-env-vars.outputs.env_SUBNETS_APPGW_IP }}
-      SUBNETS_APPGW_PRIVATE_IP_ADDRESS: ${{  needs.load-env-vars.outputs.env_SUBNETS_APPGW_PRIVATE_IP_ADDRESS }}
-      SUBNETS_AKS_NODE_IP: ${{  needs.load-env-vars.outputs.env_SUBNETS_AKS_NODE_IP }}
-      NSGS_APPGW_DESTINATION_ADDRESS_PREFIX: ${{  needs.load-env-vars.outputs.env_NSGS_APPGW_DESTINATION_ADDRESS_PREFIX }}
-      APPGW_LISTENERS_WILDCARD_BACKENDSIPS: ${{  needs.load-env-vars.outputs.env_APPGW_LISTENERS_WILDCARD_BACKENDSIPS }}
-      
-  call-workflow-k8s:
-    needs: [call-workflow-frontend,load-env-vars]
-    name: 'Calling the external K8S workflow to configure and create the project'
-    uses: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s/.github/workflows/mandatory-project-configuration-called.yaml@main
-    with:
-      PROJECT_CODE: ${{  needs.load-env-vars.outputs.env_PROJECT_CODE }}
-      LOAD_BALANCER_IP: ${{  needs.load-env-vars.outputs.env_.LOAD_BALANCER_IP }}
-      KEYCLOAK_ARGOCD_CLIENT_SECRET: ${{  needs.load-env-vars.outputs.env_.KEYCLOAK_ARGOCD_CLIENT_SECRET }}
-      CREATE_MSSQL_DB: ${{  needs.load-env-vars.outputs.env_.CREATE_MSSQL_DB }}
-      DB_ADMIN_PWD: ${{  needs.load-env-vars.outputs.env_.DB_ADMIN_PWD }}
+    - name: Check out repository code OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Inject variables for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      run: |
+        sed -i 's#VAR_TEMPLATE_LOAD_BALANCER_IP#${{ env.LOAD_BALANCER_IP }}#g' files/chart_values/nginx-ingress-controller-values.yaml
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" terraform.tfvars.json
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#g" backend_config.hcl
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#g" .github/workflows/create-dynamicepehemral-k8s.yaml
+        sed -i "s#VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE#g" .github/workflows/destroy-dynamicepehemral-k8s.yaml
+    - name: Create KEYCLOAK_ARGOCD_CLIENT_SECRET secret for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      uses: hmanzur/actions-set-secret@v2.0.0
+      with:
+        name: "OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_KEYCLOAK_ARGOCD_CLIENT_SECRET"
+        value: "${{ env.KEYCLOAK_ARGOCD_CLIENT_SECRET }}"
+        repository: 'ES-BAR-MEV'
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+        org: true
+        visibility: 'private'
+    - name: Create DB_ADMIN_PWD secret for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      if: github.event.inputs.CREATE_MSSQL_DB == 'true'
+      uses: hmanzur/actions-set-secret@v2.0.0
+      with:
+        name: "OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE_DB_ADMIN_PWD"
+        value: "${{ env.DB_ADMIN_PWD}}"
+        repository: 'ES-BAR-MEV'
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+        org: true
+        visibility: 'private'
+    - name: Enable DDBB creation for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      if: github.event.inputs.CREATE_MSSQL_DB == 'true'
+      run: |
+        sed -i 's#VAR_TEMPLATE_CREATE_MSSQL_DB#true#g' variables.tf
+    - name: Disable DDBB creation for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      if: github.event.inputs.CREATE_MSSQL_DB == 'false'
+      run: |
+        sed -i 's#VAR_TEMPLATE_CREATE_MSSQL_DB#false#g' variables.tf
+    - name: Creating cfg-applied.txt file for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      run: |
+        echo "CONFIGURATION APPLIED. DO NOT DELETE THIS FILE" >> cfg-applied.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
 
+  push_run_creation_workflow_file:
+    needs: [configure_projects]
+    name: 'Creating the projects base / frontend-aks / k8s'
+    runs-on: ubuntu-latest
+    steps:
+    - name: Check out repository code for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Create the file run_creation_workflow.txt for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-base
+      run: |
+        echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> run_creation_workflow.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
 
-#  array_file_names:
-#    runs-on: ubuntu-latest
-#    outputs:
-#      matrix: ${{ steps.matrix.outputs.value }}
-#    steps:
-#      - id: matrix
-#        run: |
-#          echo "value=[\"params/01_params.env\",\"params/02_params.env\",\"params/03_params.env\",\"params/04_params.env\",\"params/05_params.env\",\"params/06_params.env\",\"params/07_params.env\",\"params/08_params.env\",\"params/09_params.env\",\"params/10_params.env\",]" >> $GITHUB_OUTPUT
-#      - run: |
-#          echo "${{ steps.matrix.outputs.value }}"
-#  define_next_parameter_file:
-#    needs: [ array_file_names ]
-#    runs-on: ubuntu-latest
-#    outputs:
-#      thefile: ${{ steps.file_exists.outputs.value }}
-#    strategy:
-#      matrix:
-#        value: ${{fromJSON(needs.array_file_names.outputs.matrix)}}
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#      - name: Checking file existence
-#        id: check_files
-#        uses: andstor/file-existence-action@v3
-#        with:
-#          files:  '${{ matrix.value }}'
-#      - name: File does not exists
-#        if: steps.check_files.outputs.files_exists != 'true'
-#        run: |
-#          echo "FILE DOES NOT EXISTS"
-#      - name: File exists
-#        id: file_exists
-#        if: steps.check_files.outputs.files_exists == 'true'
-#        run: |
-#          echo "value=${{ matrix.value }}" >> $GITHUB_OUTPUT
-#  print:
-#    needs: [ define_next_parameter_file ]
-#    runs-on: ubuntu-latest
-#    steps:
-#      - run: |
-#          echo "${{ needs.define_next_parameter_file.outputs.thefile }}"
-#
-#
-#  setup_parameters:
-#    needs: [ define_next_parameter_file, format_prj_coode ]
-#    runs-on: ubuntu-latest
-#    env:
-#      PROJECT_CODE_LOWERCASE: ${{ needs.format_prj_coode.outputs.prj_code_lower }}
-#      PROJECT_CODE_UPPERCASE: ${{ needs.format_prj_coode.outputs.prj_code_upper }}
-#    steps:
-#      - name: Check out repository code
-#        uses: actions/checkout@v3
-#        with:
-#          token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
-#      - name: Rename file 
-#        run: mv ${{ needs.define_next_parameter_file.outputs.thefile }} "params/${{ env.PROJECT_CODE_UPPERCASE}}_params.env"
-#      - name: Inject variables
-#        run: |
-#          sed -i "s#VAR_TEMPLATE_PROJECT_CODE_LOWERCASE#${{ env.PROJECT_CODE_LOWERCASE}}#g" params/${{ env.PROJECT_CODE_UPPERCASE}}_params.env
-#      - name: Push to remote
-#        run: |
-#          git config --global user.name "Configure Project"
-#          git config --global user.email "configure.project@atos.net"
-#          git add -A
-#          git commit -m "Generation parameters file"
-#          git push
+    - name: Check out repository code for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Create the file run_creation_workflow.txt for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-frontend-aks
+      run: |
+        echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> run_creation_workflow.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
+
+    - name: Check out repository code for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      uses: actions/checkout@v4
+      with:
+        repository: ES-BAR-MEV/IDM-IAC-DYNAMIC-EPHEMERAL-OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+        token: ${{ secrets.DYNAMICEPHEMERAL_WORKFLOW_TOKEN }}
+    - name: Create the file run_creation_workflow.txt for OWN_VAR_TEMPLATE_PROJECT_CODE_UPPERCASE-k8s
+      run: |
+        echo "THIS REPO HAS BEEN CALLED FROM SHUTTLE WORKFLOW. DO NOT DELETE IT" >> run_creation_workflow.txt
+        git config --global user.name "Configure Project"
+        git config --global user.email "configure.project@atos.net"
+        git add -A
+        git commit -m "Confirmation of project configuration"
+        git push
